spring:
  application:
    name: lifeasgame

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 4
      validation-timeout: 2000
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 50

      shutdown:
        await-termination: true
        await-termination-period: 30s

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate.jdbc.time_zone: Asia/Seoul

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: false

  jackson:
    time-zone: Asia/Seoul

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true

logging:
  level:
    root: info
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF
    org.hibernate.type.descriptor.sql: WARN

lifeasgame:
  web:
    cors:
      allowed-origins: ${LIFEASGAME_WEB_ALLOWED_ORIGINS:http://localhost:3000}

app:
  error:
    docs:
      base: "/errors"
      ext: ""

    mask-fields: [password, secret, token]
    mask-props: [password, secret, token]

    expose-db-reason: false

  outbox:
    enabled: ${OUTBOX_ENABLED:true}
    fixed-delay-ms: 500
    batch-size: 50
    max-attempts: 10
    retry-delay-ms: 1000
    lease-duration-ms: 30000
    instance-id: ${OUTBOX_INSTANCE_ID:${spring.application.name}-${random.uuid}}

lag:
  level-curve:
    max-level: 200
    base-req-lv1: 100

    brackets:
      - { from: 1, to: 30, mul: 1.10, add: 25 }
      - { from: 31, to: 100, mul: 1.12, add: 100 }
      - { from: 101, to: 200, mul: 1.20, add: 500 }
#      - { from: 201, to: 260, mul: 1.25, add: 1000 }
#      - { from: 261, to: 300, mul: 1.30, add: 2500 }
