package online.lifeasgame.economy.domain.event;

public enum EconomyEventType {
    LISTING_OPENED,
    LISTING_RESERVED,
    LISTING_PURCHASED,
    LISTING_CANCELED,
    LISTING_EXPIRED,
    SHOP_ITEM_CREATED,
    SHOP_ITEM_TOGGLED,
    SHOP_PURCHASE_RESERVED,
    SHOP_PURCHASE_COMPLETED,
    SHOP_RESERVATION_EXPIRED,
    TOPUP_COMPLETED,
    WALLET_ADJUSTED,
    FULFILLMENT_READY
}
