-- CLEAN INSTALL ONLY. Do not execute this migration against an existing database.
-- Existing databases must follow docs/database/flyway_baseline_runbook.md.
--
-- Source: current Hibernate/JPA mappings, exported with Hibernate 6.6 MySQLDialect.
-- Creation order: all application and collection tables first (alphabetical),
-- then secondary indexes/unique constraints, and finally foreign keys.

SET NAMES utf8mb4;

create table achievements (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, code varchar(60) not null, name varchar(60) not null, category enum ('COLLECTION','COMBAT','DAILY','ECONOMY','EXPLORATION','SKILL','SOCIAL','STORY') not null, desc_md tinytext, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table certification (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, issuer varchar(255) not null, name varchar(255) not null, category enum ('CLOUD','DATA','DATABASE','DESIGN','FINANCE','LANGUAGE','MANAGEMENT','NETWORK','OTHER','PROGRAMMING','SECURITY') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table channel_participants (channel_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, user_id bigint not null, version bigint, role enum ('ADMIN','MEMBER','MODERATOR','OWNER') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table chat_channels (read_only bit not null, context_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, version bigint, name varchar(60), type enum ('ADMIN','FRIEND','GLOBAL','GUILD','PARTY','SYSTEM') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table chat_messages (edited bit not null, channel_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, sender_id bigint not null, updated_at datetime(6) not null, version bigint, content LONGTEXT not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table collection_log_tags (collection_log_id bigint not null, tag varchar(50)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table collection_logs (quantity_value integer not null, created_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, updated_at datetime(6) not null, acquired_from varchar(100), condition_note varchar(100), title_original varchar(255), title_value varchar(255) not null, category enum ('BOOK','CARD','COIN','FIGURE','GAME','OTHER','STAMP') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table combat_events (created_at datetime(6) not null, id bigint not null auto_increment, occurred_at datetime(6) not null, player_id bigint not null, updated_at datetime(6) not null, event_type varchar(30) not null, payload json not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table coop_history (created_at datetime(6) not null, id bigint not null auto_increment, partner_id bigint, party_id bigint, player_id bigint not null, updated_at datetime(6) not null, context json, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table equipment_slots (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, code varchar(40) not null, name varchar(40) not null, category enum ('CHEST','FEET','HANDS','HEAD','LEGS','NECK','RING','TRINKET','WEAPON') not null, role enum ('LEFT','MAIN','OFFHAND','RIGHT','SINGLE') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table exercise_logs (calories integer, distance_km float(53), duration_minutes integer not null, exercised_on date not null, created_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, updated_at datetime(6) not null, memo varchar(200), category enum ('CYCLING','GYM','OTHER','RUNNING','SWIMMING','WALKING','YOGA') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table exp_history (delta integer not null, created_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, updated_at datetime(6) not null, context json, reason enum ('ADMIN_ADJUST','COMBAT','CRAFTING','DAILY_BONUS','ETC','PURCHASE_REFUND','QUEST_REWARD') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table follows (blocked bit not null, muted bit not null, created_at datetime(6) not null, follow_id bigint not null auto_increment, player_id bigint not null, target_player_id bigint not null, updated_at datetime(6) not null, state enum ('FOLLOWING','STOPPED') not null, primary key (follow_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table guild_members (created_at datetime(6) not null, guild_id bigint not null, guild_member_id bigint not null auto_increment, joined_at datetime(6) not null, player_id bigint not null, updated_at datetime(6) not null, role enum ('LEADER','MEMBER','OFFICER') not null, primary key (guild_member_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table guild_tags (guild_id bigint not null, tag_value varchar(64) not null, primary key (guild_id, tag_value)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table guild_wait_members (created_at datetime(6) not null, expires_at datetime(6), guild_id bigint not null, guild_wait_member_id bigint not null auto_increment, player_id bigint not null, requested_at datetime(6) not null, updated_at datetime(6) not null, version bigint not null, message varchar(1000), status enum ('APPROVED','CANCELLED','PENDING','REJECTED') not null, type enum ('INVITATION','JOIN_REQUEST') not null, primary key (guild_wait_member_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table guilds (max_members integer not null, created_at datetime(6) not null, guild_id bigint not null auto_increment, leader_player_id bigint not null, player_id bigint not null, updated_at datetime(6) not null, emblem_bg_color varchar(16), code_value varchar(32) not null, name_original varchar(128) not null, name_value varchar(128) not null, emblem_image_url varchar(512), description_md text, join_policy enum ('APPROVAL','INVITE_ONLY','OPEN') not null, status enum ('ACTIVE','DISBANDED','INACTIVE') not null, visibility enum ('PRIVATE','PUBLIC') not null, primary key (guild_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table hobbies (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, name varchar(255) not null, category enum ('ARTS','BAKING','BOARD_GAMES','COOKING','CRAFTS','FITNESS','GAMING','LANGUAGE','MUSIC','OUTDOORS','PHOTOGRAPHY','READING','SPORTS','TECH','TRAVEL','VOLUNTEERING','WELLNESS','WRITING') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table inventory_entries (bound bit not null, durability integer, quantity integer not null, slot_index integer not null, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, player_id bigint not null, updated_at datetime(6) not null, inst_attrs json, rarity enum ('COMMON','EPIC','LEGENDARY','RARE','UNCOMMON') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table items (max_durability integer, max_stack integer not null, stackable bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, name varchar(80) not null, base_attrs json, category enum ('ACCESSORY','ARMOR','CONSUMABLE','MATERIAL','MISC','QUEST','WEAPON') not null, rarity enum ('COMMON','EPIC','LEGENDARY','RARE','UNCOMMON') not null, type enum ('BOW','CHEST','ETC','HELMET','HERB','KEY','ORE','POTION','RING','SCROLL','SHIELD','STAFF','SWORD') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table listings (active_flag integer, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint, item_inst_id bigint not null, price bigint, reservation_expires_at datetime(6), reserved_by bigint, seller_player_id bigint not null, updated_at datetime(6) not null, version bigint, reservation_token varchar(36), reserved_hold_id varchar(36), currency enum ('GEM','GOLD'), status enum ('CANCELED','EXPIRED','OPEN','RESERVED','SOLD') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table mailbox_entries (bound bit not null, durability integer, quantity integer not null, slot_index integer not null, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, player_id bigint not null, updated_at datetime(6) not null, inst_attrs json, rarity enum ('COMMON','EPIC','LEGENDARY','RARE','UNCOMMON') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table media_log_tags (media_log_id bigint not null, tag varchar(50)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table media_logs (finished_on date, progress_current integer not null, progress_total integer not null, rating_score float(53) not null, rewatch_count integer not null, started_on date, created_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, updated_at datetime(6) not null, title_original varchar(255), title_value varchar(255) not null, category enum ('ANIME','BOOK','GAME','MOVIE','MUSIC','SERIES','WEBTOON') not null, status enum ('COMPLETED','DROPPED','ON_HOLD','PLANNED','WATCHING') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table parties (max_members integer not null, created_at datetime(6) not null, leader_player_id bigint not null, party_id bigint not null auto_increment, player_id bigint not null, updated_at datetime(6) not null, banner_bg_color varchar(16), code_value varchar(32) not null, name_original varchar(128) not null, name_value varchar(128) not null, banner_image_url varchar(512), description_md text, join_policy enum ('APPROVAL','INVITE_ONLY','OPEN') not null, status enum ('ACTIVE','DISBANDED','INACTIVE') not null, visibility enum ('PRIVATE','PUBLIC') not null, primary key (party_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table party_members (created_at datetime(6) not null, joined_at datetime(6) not null, party_id bigint not null, party_member_id bigint not null auto_increment, player_id bigint not null, updated_at datetime(6) not null, role enum ('LEADER','MEMBER','OFFICER') not null, primary key (party_member_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table party_tags (party_id bigint not null, tag_value varchar(64) not null, primary key (party_id, tag_value)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table party_wait_members (created_at datetime(6) not null, expires_at datetime(6), party_id bigint not null, party_wait_member_id bigint not null auto_increment, player_id bigint not null, requested_at datetime(6) not null, updated_at datetime(6) not null, message varchar(1000), status enum ('APPROVED','CANCELLED','PENDING','REJECTED') not null, type enum ('INVITATION','JOIN_REQUEST') not null, primary key (party_wait_member_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player (agi_stat integer not null, dex_stat integer not null, hp_cap integer not null, hp_cur integer not null, int_stat integer not null, level integer not null, luc_stat integer not null, mp_cap integer not null, mp_cur integer not null, str_stat integer not null, vit_stat integer not null, created_at datetime(6) not null, exp bigint not null, guild_id bigint, id bigint not null auto_increment, title_id bigint, updated_at datetime(6) not null, user_id bigint not null, version bigint, gender varchar(20), job varchar(30), name varchar(40) not null, extra_stats json, status_effects varchar(255), primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player_achievements (achievement_id bigint not null, acquired_at datetime(6) not null, created_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player_certifications (acquired_date date, expires_date date, certification_id bigint not null, created_at datetime(6) not null, granted_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player_equipment (created_at datetime(6) not null, equipped_at datetime(6), id bigint not null auto_increment, item_inst_id bigint, player_id bigint not null, slot_id bigint not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player_hobbies (proficiency integer not null, started_on date, hobby_id bigint not null, id bigint not null auto_increment, player_id bigint not null, xp bigint not null, custom_name varchar(60) not null, detail varchar(200), status enum ('ACTIVE','DROPPED','PAUSED') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player_inventory (capacity_slots integer not null, created_at datetime(6) not null, player_id bigint not null, updated_at datetime(6) not null, version bigint, primary key (player_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player_mailbox (capacity_slots integer not null, created_at datetime(6) not null, player_id bigint not null, updated_at datetime(6) not null, version bigint, primary key (player_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player_skill_points (available_sp integer not null, created_at datetime(6) not null, player_id bigint not null, updated_at datetime(6) not null, version bigint, primary key (player_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player_skills (level integer not null, id bigint not null auto_increment, player_id bigint not null, skill_id bigint not null, version bigint, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table player_titles (acquired_at datetime(6) not null, created_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, title_id bigint not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table price_snapshots (sample_size integer not null, avg_price bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, taken_at datetime(6) not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table quest_acceptances (period_end date not null, period_start date not null, progress_value integer not null, completed_at datetime(6), created_at datetime(6) not null, guild_id bigint, id bigint not null auto_increment, party_id bigint, player_id bigint not null, quest_id bigint not null, updated_at datetime(6) not null, version bigint, idempotency_key varchar(120), status enum ('CANCELED','DONE','IN_PROGRESS') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table quest_clear_log (completed_at datetime(6) not null, created_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, quest_id bigint not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table quests (reward_exp integer not null, target_value integer not null, created_at datetime(6) not null, due_at datetime(6), id bigint not null auto_increment, updated_at datetime(6) not null, code varchar(80) not null, title_id varchar(120) not null, reward_stats json not null, category enum ('GUILD','MAIN','PARTY','RECOMMENDED','REPEAT') not null, description_md tinytext, repeat_rule enum ('DAILY','MONTHLY','NONE','WEEKLY'), target_type enum ('COUNT','MINUTES','SCORE') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table shop_items (available bit not null, global_stock_limit integer, per_player_limit integer, reservation_ttl_sec integer, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, price bigint, updated_at datetime(6) not null, version bigint, currency enum ('GEM','GOLD'), primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table shop_purchases (quantity integer not null, created_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, reservation_expires_at datetime(6), shop_item_id bigint not null, total_price bigint, updated_at datetime(6) not null, reservation_token varchar(36), wallet_hold_id varchar(36), currency enum ('GEM','GOLD'), status enum ('CANCELED','COMPLETED','EXPIRED','REQUESTED','RESERVED') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table skill_edges (req_level integer not null, created_at datetime(6) not null, from_skill_id bigint not null, id bigint not null auto_increment, to_skill_id bigint not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table skills (max_level integer not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, code varchar(60) not null, name varchar(80) not null, base_effect json, kind enum ('ACTIVE','PASSIVE') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table stat_change_log (created_at datetime(6) not null, id bigint not null auto_increment, player_id bigint not null, updated_at datetime(6) not null, reason varchar(40) not null, changes json not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table titles (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, code varchar(60) not null, name varchar(60) not null, category enum ('ACHIEVEMENT','EVENT','OTHER','QUEST','RANKED','SPECIAL') not null, desc_md tinytext, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table trades (fee_bps integer not null, buyer_player_id bigint not null, created_at datetime(6) not null, fee bigint, id bigint not null auto_increment, item_inst_id bigint not null, listing_id bigint not null, price bigint, seller_player_id bigint not null, seller_proceeds bigint, updated_at datetime(6) not null, currency enum ('GEM','GOLD'), fee_currency enum ('GEM','GOLD'), seller_proceeds_currency enum ('GEM','GOLD'), primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table user_settings (volume integer not null, created_at datetime(6) not null, updated_at datetime(6) not null, user_id bigint not null, flags json, ui_layout json, primary key (user_id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table users (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, nickname varchar(20) not null, email varchar(254) not null, password_hash varchar(255) not null, status enum ('ACTIVE','BANNED','DELETED','PENDING_EMAIL_VERIFICATION') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table wallet_balances (amount bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, wallet_id bigint not null, currency enum ('GEM','GOLD') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table wallet_holds (amount bigint not null, created_at datetime(6) not null, expires_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, wallet_id bigint not null, hold_id varchar(36) not null, reason varchar(100), currency enum ('GEM','GOLD') not null, status enum ('CANCELED','COMMITTED','EXPIRED','OPEN') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
create table wallets (created_at datetime(6) not null, id bigint not null auto_increment, owner_id bigint not null, updated_at datetime(6) not null, version bigint, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
-- Secondary indexes and unique constraints.
alter table achievements add constraint UK9qqq83lafche8dr9o229kc9tg unique (code);
create index idx_channel_user on channel_participants (user_id);
alter table channel_participants add constraint uq_channel_user unique (channel_id, user_id);
create index idx_channel_type on chat_channels (type);
create index idx_channel_context on chat_channels (context_id);
create index idx_message_channel_seq on chat_messages (channel_id, id);
create index idx_message_channel_time on chat_messages (channel_id, created_at, id);
create index idx_message_sender on chat_messages (sender_id);
create index idx_collection_player on collection_logs (player_id);
create index idx_collection_category on collection_logs (category);
create index idx_player_time4 on combat_events (player_id, occurred_at);
create index idx_party_time3 on coop_history (party_id, created_at);
create index idx_player_time3 on coop_history (player_id, created_at);
alter table equipment_slots add constraint UK3580sud7mp8k4j0gobcyqot4l unique (code);
create index idx_exercise_player on exercise_logs (player_id);
create index idx_exercise_category on exercise_logs (category);
create index idx_exercise_exercised_on on exercise_logs (exercised_on);
create index idx_player_time on exp_history (player_id, created_at);
create index idx_follow_player on follows (player_id);
create index idx_follow_target_player on follows (target_player_id);
alter table follows add constraint uk_follower_followee unique (player_id, target_player_id);
create index idx_guild_member_guild on guild_members (guild_id);
create index idx_guild_member_player on guild_members (player_id);
alter table guild_members add constraint uk_guild_member_guild_player unique (guild_id, player_id);
create index idx_wait_guild on guild_wait_members (guild_id);
create index idx_wait_guild_player on guild_wait_members (player_id);
alter table guilds add constraint UKc44qhgdprwxapo7co98a0fk3 unique (code_value);
alter table inventory_entries add constraint uq_inventory_slot unique (player_id, slot_index);
create index idx_item_name on items (name);
alter table items add constraint UKmnhl79u3u6jdvutuoeq54stne unique (name);
create index idx_status_price on listings (status, price);
create index idx_seller on listings (seller_player_id);
create index idx_item on listings (item_id);
create index idx_reservation_exp on listings (reservation_expires_at);
alter table listings add constraint uq_active_item unique (item_inst_id, active_flag);
alter table mailbox_entries add constraint uq_mailbox_slot unique (player_id, slot_index);
create index idx_media_player on media_logs (player_id);
create index idx_media_category on media_logs (category);
create index idx_media_status on media_logs (status);
alter table parties add constraint UKoix8c6oc2ouo5n3xxbka6ne69 unique (code_value);
create index idx_party_member_party on party_members (party_id);
create index idx_party_member_player on party_members (player_id);
create index idx_wait_party on party_wait_members (party_id);
create index idx_wait_party_player on party_wait_members (player_id);
create index player_idx_user on player (user_id);
alter table player add constraint UKfpxwfe7n29rwsbyu5p1wl2mq1 unique (user_id);
alter table player_achievements add constraint uq_player_achv unique (player_id, achievement_id);
create index idx_cert_player on player_certifications (player_id);
alter table player_certifications add constraint uq_player_cert unique (player_id, certification_id);
alter table player_equipment add constraint uq_player_slot unique (player_id, slot_id);
create index idx_hobby_player on player_hobbies (player_id);
alter table player_hobbies add constraint uq_player_hobby unique (player_id, hobby_id);
alter table player_skills add constraint pk_player_skill unique (player_id, skill_id);
alter table player_titles add constraint uq_player_title unique (player_id, title_id);
create index idx_snapshot_item_time on price_snapshots (item_id, taken_at);
alter table price_snapshots add constraint uq_item_time unique (item_id, taken_at);
create index idx_qa_player on quest_acceptances (player_id);
create index idx_qa_quest on quest_acceptances (quest_id);
create index idx_qa_status on quest_acceptances (status);
alter table quest_acceptances add constraint uq_repeat unique (player_id, quest_id, period_start, period_end);
create index idx_player_quest on quest_clear_log (player_id, quest_id, completed_at);
alter table quests add constraint UKfiypv7mlexb02d6cw4ym91k5h unique (code);
alter table shop_items add constraint uq_shop_item unique (item_id, currency);
create index idx_shop_item on shop_purchases (shop_item_id);
create index idx_shop_player on shop_purchases (player_id);
create index idx_shop_status on shop_purchases (status);
alter table shop_purchases add constraint uq_shop_res_token unique (reservation_token);
alter table skill_edges add constraint uq_edge unique (from_skill_id, to_skill_id);
alter table skills add constraint UK2b0y7lhl8xlfp9t6hcncyxjqq unique (code);
create index idx_player_time2 on stat_change_log (player_id, created_at);
alter table titles add constraint UKp66yoxalyk0n7xgubadcbvw0f unique (code);
create index idx_buyer_time on trades (buyer_player_id, created_at);
create index idx_seller_time on trades (seller_player_id, created_at);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create index idx_balance_wallet on wallet_balances (wallet_id);
alter table wallet_balances add constraint uq_wallet_balance_wallet_currency unique (wallet_id, currency);
create index idx_hold_wallet on wallet_holds (wallet_id);
create index idx_hold_expires on wallet_holds (expires_at);
alter table wallet_holds add constraint UK4pvblbpln9x8iqhrs5h6l8no7 unique (hold_id);
alter table wallets add constraint uq_wallet_owner unique (owner_id);
-- Foreign keys are added after every table exists.
alter table channel_participants add constraint FK19jte0ydrq8jfj0ylgs05dwd1 foreign key (channel_id) references chat_channels (id);
alter table chat_messages add constraint FK7d773200rrat1tg8s6vw5g36f foreign key (channel_id) references chat_channels (id);
alter table collection_log_tags add constraint FKcdy8f3gu9e57widftko0psw5x foreign key (collection_log_id) references collection_logs (id);
alter table guild_members add constraint FK5spmkoxf20vqdvbj4vu4guvx foreign key (guild_id) references guilds (guild_id);
alter table guild_tags add constraint FK97q23g851x128csvgawkncubg foreign key (guild_id) references guilds (guild_id);
alter table guild_wait_members add constraint FKgpmu7ivagctltjbnds4jbrwk4 foreign key (guild_id) references guilds (guild_id);
alter table inventory_entries add constraint FKko5xy9pakstl4edw92hbbhn12 foreign key (player_id) references player_inventory (player_id);
alter table mailbox_entries add constraint FKdvtej8whvyqmtwn1i4m65w47 foreign key (player_id) references player_mailbox (player_id);
alter table media_log_tags add constraint FKcxui9ll75ymw610a3wfrfe76q foreign key (media_log_id) references media_logs (id);
alter table party_members add constraint FK8t7tw0lrh904ld026ludm2vm3 foreign key (party_id) references parties (party_id);
alter table party_tags add constraint FKbsutdo5uyjhxhy1xn9cyo27dv foreign key (party_id) references parties (party_id);
alter table party_wait_members add constraint FK5imx8cxjmvsywtvikj5qfj0k2 foreign key (party_id) references parties (party_id);
alter table wallet_balances add constraint FKb7vxgyry3jrwtycpd4nipqu38 foreign key (wallet_id) references wallets (id);
alter table wallet_holds add constraint FK5rberb7jrra19mks5xau4964l foreign key (wallet_id) references wallets (id);

